
spring:
  datasource:
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/komilles
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/komilles



openai:
  api_key: ${API_KEY}