
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/komilles
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_NAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/komilles
